---
- name: Install package
  apt: 
    name: mariadb-server
    state: present
- name: Change bind-address
  copy:
    src: 50-server.cnf
    dest: /etc/mysql/mariadb.conf.d/50-server.cnf
    owner: root
    group: root 
    mode: '0644'
- name: Change lines
  lineinfile:
    line: "{{ item.line }}"
    regexp: "{{ item.regexp }}"
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
  loop:
  - line: bind-address = {{ ansible_facts.eth0.ipv4.address }}
    regexp: bind-address = IP_ADDRESS
  - line: wsrep_node_address="{{ ansible_facts.hostname }}"
    regexp: wsrep_node_address="DB_HOSTNAME"  
- name: Run galera
  shell: galera_new_cluster
  when: ansible_facts['hostname'] == "db1"
  run_once: true
- name: Wait
  wait_for:
    timeout: 20 
- name: Start mariadb on db2
  service:
    name: mariadb
    state: restarted
  when: ansible_facts['hostname'] == "db2"
- name: Wait
  wait_for:
    timeout: 20 
- name: Start mariadb on db3
  service:
    name: mariadb
    state: restarted
  when: ansible_facts['hostname'] == "db3"
- name: Wait
  wait_for:
    timeout: 20
  
- name: Create db
  shell: >
     mysql -e "CREATE DATABASE wordpress;" &&
     mysql -e "CREATE USER 'wordpress'@'%' IDENTIFIED BY 'Otus123';" &&
     mysql -e "GRANT ALL ON wordpress.* TO 'wordpress'@'%';" &&
     mysql -e "CREATE USER 'haproxy'@'%';"
  when: ansible_facts['hostname'] == "db1"
  ignore_errors: true
  run_once: true

