---
# tasks file for preconfig
- name: Copy hosts
  copy:
    src: hosts
    dest: /etc/hosts
    owner: root
    group: root
    mode: '0644'
    backup: yes
- name: Update
  apt:
    update_cache: true
    cache_valid_time: 3600
- name: Upgrade
  apt: 
    upgrade: true
- name: Wait 20
  wait_for: 
    timeout: 20